SELECT Essn AS Manager_Ssn, COUNT(1) AS No_Of_Projects
FROM COMPANY.WORKS_ON WHERE Essn IN (
	SELECT Mgr_Ssn FROM COMPANY.DEPARTMENT WHERE Dnumber IN (
		SELECT DISTINCT Dnum FROM COMPANY.PROJECT WHERE Pname = "ProductY"
	)
)
GROUP BY Essn;